
# Example config file.
# cexec uses one config for both server and client mode.

# Peer identity record broadcast frequency.
# This is how often you tell a network that you exist.
pid_broadcast_frequency = "5m"




